server:
  port: 8083
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      group-id: stream
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      commit:
        interval:
          ms: 1 # no commit delay, default is 30 seconds
